import '@radix-ui/themes/styles.css';
import './globals.css';
import './theme-config.css';
import { Inter } from 'next/font/google';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import type { Metadata } from 'next';
import NavBar from './NavBar';
import AuthProvider from './auth/Provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
          <Theme
            // appearance="light"
            // appearance="dark"
            accentColor="teal"
            radius="small"
            scaling="95%"
          >
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
            {/* <ThemePanel /> */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
